// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("StockPriceanalysis")>]
[<assembly: AssemblyProductAttribute("StockPriceAnalysis")>]
[<assembly: AssemblyDescriptionAttribute("Take Some Stock Data and apply simple statistics")>]
[<assembly: AssemblyVersionAttribute("1.0.1")>]
[<assembly: AssemblyFileVersionAttribute("1.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "StockPriceanalysis"
    let [<Literal>] AssemblyProduct = "StockPriceAnalysis"
    let [<Literal>] AssemblyDescription = "Take Some Stock Data and apply simple statistics"
    let [<Literal>] AssemblyVersion = "1.0.1"
    let [<Literal>] AssemblyFileVersion = "1.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
